
################################################################################
server:
  port: 48081
################################################################################

################################################################################
spring:

  profiles:
      include: devdb

################################################################################
