
################################################################################
server:
  port: 48081
################################################################################

################################################################################
spring:

  datasource:
    hikari:
      username: imagetalk
      password: Tbwdlalwlxhr1!
      maximum-pool-size: 10
      connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33306/it_db

################################################################################
