
################################################################################
server:
  port: 7082
################################################################################

################################################################################
spring:

  profiles:
    #include: proddb

  datasource:
    hikari:
      username: imagetalk
      password: Tbwdlalwlxhr1!
      maximum-pool-size: 10
      connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33306/it_db

  jpa:
    hibernate:
      ddl-auto: none                                       # 테이블 검사안함
    defer-datasource-initialization: false                 # table 없으면 자동 생성 안함

  thymeleaf:
    cache: true
  devtools:
    restart:
      enabled: false						               # 소스파일에 변화가 있을 때 자동으로 서버 재 시작 설정

  sql:
    init:
      mode: never                                          # data.sql 실행 안함


################################################################################