
################################################################################
server:
  port: 48082
################################################################################

################################################################################
spring:

  profiles:
    include: proddb

  thymeleaf:
    cache: true
  devtools:
    restart:
      enabled: false						# 소스파일에 변화가 있을 때 자동으로 서버 재 시작 설정
    livereload:
      enabled: true							# 정적 리소스에 변화가 있을 때 바로 반영
################################################################################