################################################################################
# Usage:
#import org.springframework.beans.factory.annotation.Value;
#@Value("${test.app}")
#private String appStr;
################################################################################

################################################################################
server:
  name: mc_server2
################################################################################